# -*- coding: utf-8 -*-
"""Churn_Clf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rnzULs0555FYEclZIYKZkdfUU1YnpYjv

# <div align="center">**CUSTOMER CHURN PREDICTION**</div>  

### **MỰC TIÊU DỰ ÁN**

- **Giảm tỷ lệ khách hàng rời bỏ (churn)**: Chủ động dự đoán khách hàng có khả năng rời bỏ sớm, từ đó đưa ra các chính sách giữ chân kịp thời.

- **Tối ưu chi phí giữ chân khách hàng:** Thay vì dàn trải nguồn lực, ngân hàng tập trung chính xác vào nhóm khách hàng có nguy cơ cao nhất.

- **Nâng cao trải nghiệm khách hàng:** Hiểu rõ yếu tố nào dẫn đến khách hàng rời bỏ, từ đó cải thiện dịch vụ, sản phẩm một cách chính xác và hiệu quả nhất.

- **Gia tăng lợi thế cạnh tranh:** Sử dụng công nghệ (AI/ML) để nhanh chóng phát hiện và phản ứng kịp thời trước biến động hành vi khách hàng, từ đó chiếm ưu thế trước các đối thủ cạnh tranh trên thị trường.
  
### **DỮ LIỆU ĐẦU VÀO**
* **Thông tin khách hàng**

  * Định danh: CustomerId

  * Nhân khẩu học: Gender, Age

  * Quan hệ với ngân hàng: Tenure (số năm gắn bó)

* **Hoạt động tài chính**

  * Điểm tín dụng: CreditScore

  * Số dư tài khoản: Balance

  * Thu nhập ước tính: EstimatedSalary

  * Sản phẩm đang sử dụng: NumOfProducts, HasCrCard

* **Hành vi sử dụng dịch vụ**

  * Tần suất đăng nhập: LoginFrequency

  * Giao dịch ra ngoài hệ thống: ExternalTransfers

  * Tình trạng hoạt động: IsActiveMember

* **Biến mục tiêu (Target)**

  * Rời bỏ dịch vụ: Exited (1 = đã rời, 0 = chưa)
      
### **NỘI DUNG CHÍNH**
* **Thiết lập dự án**

* **Tiền xử lý & Feature Engineering**


* **EDA cơ bản**


* **Xây mô hình dự đoán churn**


* **Giải thích mô hình với SHAP**

* **Tạo khoảng tin cậy với MAPIE**

---
# **THIẾT LẬP DỰ ÁN**
---

# **1. Load dữ liệu**
"""

import pandas as pd

# Đọc file dữ liệu
df = pd.read_excel("/content/ChurnDataset.xlsx")

# Hiển thị 5 dòng đầu tiên
df.head()

"""
# **2. Kiểm tra định dạng dữ liệu , shape , missing value**"""

# Kiểm tra số dòng, cột
print("Shape:", df.shape)

# Xem thông tin kiểu dữ liệu, non-null
df.info()

# Tính tỉ lệ thiếu trên mỗi cột
missing_ratio = df.isnull().mean().sort_values(ascending=False)

# Hiển thị các cột có giá trị thiếu
missing_ratio[missing_ratio > 0]

"""---
# **TIỀN XỬ LÝ & FEATURE ENGINEERING**
---

# **1. Mapping biến phân loại ( Gender )**
"""

import json

gender_map = {"Male": 1, "Female": 0}
df["Gender"] = df["Gender"].map(gender_map)

with open("gender_map.json", "w") as f:
    json.dump(gender_map, f)

"""

# **2. Feature Engineering**

Tạo ra các biến mới từ các biến gốc để mô hình có thêm “góc nhìn” mới về hành vi khách hàng :
 - Ý tưởng: Nếu khách có số dư cao nhưng chỉ dùng ít sản phẩm → tiềm năng chưa khai thác hết → có thể là dấu hiệu churn.
 - So sánh giữa thời gian khách hàng gắn bó và tần suất tương tác → khách gắn bó lâu nhưng ít login → có nguy cơ bỏ đi.
 -  Một khách hàng trẻ nhưng có thu nhập cao có thể được ưu tiên hơn → mô hình học được sự khác biệt giữa "khách VIP tiềm năng" và khách thường.
 - Login nhiều nhưng ít chuyển khoản → có thể chỉ truy cập xem, không thật sự tương tác tài chính.
  
  Dùng để phân loại hành vi “ngó chơi” vs “giao dịch thật”.

"""

df["BalancePerProduct"] = df["Balance"] / (df["NumOfProducts"] + 1e-5)
df["ActivityPerTenure"] = df["LoginFrequency"] / (df["Tenure"] + 1)
df["SalaryPerAge"] = df["EstimatedSalary"] / (df["Age"] + 1)
df["TransferLoginRatio"] = df["ExternalTransfers"] / (df["LoginFrequency"] + 1)
df["IsActiveCredit"] = ((df["IsActiveMember"] == 1) & (df["CreditScore"] >= 700)).astype(int)

"""##Scale dữ liệu"""

from sklearn.preprocessing import StandardScaler

X = df.drop(columns="Exited")
y = df["Exited"]

numeric_features = X.select_dtypes(include=["float64", "int64"]).columns

scaler = StandardScaler()
X_scaled = X.copy()
X_scaled[numeric_features] = scaler.fit_transform(X[numeric_features])

"""---
# **EDA CƠ BẢN**
---
"""

df.head(5)

"""
# **1. Check phân thông số và phân vị các cột để biết có cần lọc outlier hay không**"""

df.describe()

"""

# **2. Các cột được lựa chọn để xử lý outlier**

"""

# Các cột cần xử lý outlier
feature_engineered = [
    "BalancePerProduct",
    "ActivityPerTenure",
    "SalaryPerAge",
    "TransferLoginRatio"
]

# Tạo log để theo dõi số dòng bị clip
outlier_log = {}

for col in feature_engineered:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    before = df[col].copy()
    df[col] = df[col].clip(lower, upper)

    clipped = ((before < lower) | (before > upper)).sum()
    outlier_log[col] = clipped

# In log kết quả
for col, clipped in sorted(outlier_log.items(), key=lambda x: x[1], reverse=True):
    print(f"{col:25s} → {clipped} dòng bị clip")

"""# **3. Vẽ biểu đồ phân phối để quan sát dữ liệu sau khi cắt outlier**"""

import matplotlib.pyplot as plt
import seaborn as sns

# Chỉ lấy các cột dạng số (loại bỏ ID / string / object)
numeric_cols = df.select_dtypes(include=['number']).columns

# Plot
plt.figure(figsize=(20, len(numeric_cols) * 2.5))
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(len(numeric_cols), 3, i)
    sns.histplot(data=df, x=col, bins=30, kde=True, color='skyblue')
    plt.title(f"Phân phối: {col}", fontsize=10)
    plt.xlabel("")
    plt.tight_layout()

plt.suptitle(" Biểu đồ phân phối các biến số", fontsize=14, y=1.02)
plt.show()

"""

# **4. Kiểm tra tương quan giữa các biến**


 - Dùng ma trận tương quan để kiểm tra và lọc các biến có độ tương quan quá lớn với nhau
 - Mutual Infomation (Thông tin tương hỗ) : Để check tương quan giữa các biến với đầu ra ( Exited )"""

import seaborn as sns
import matplotlib.pyplot as plt

# Tính hệ số tương quan Pearson
corr_matrix = df.corr(numeric_only=True)

# Vẽ heatmap
plt.figure(figsize=(14, 12))
sns.heatmap(corr_matrix,
            annot=True,
            fmt=".2f",
            cmap="coolwarm",
            center=0,
            linewidths=0.5,
            cbar_kws={"shrink": 0.8})
plt.title("Correlation Matrix - Full Features (Pearson)", fontsize=16)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

from sklearn.feature_selection import mutual_info_classif

X_all = df.drop(columns="Exited")
y_all = df["Exited"]

mi_scores = mutual_info_classif(X_all.fillna(0), y_all, discrete_features='auto')
mi_series = pd.Series(mi_scores, index=X_all.columns).sort_values(ascending=False)

# Hiển thị top features
print(mi_series)

# Plot MI scores
mi_series.plot(kind='barh', figsize=(10, 8))
plt.title("Mutual Information with 'Exited'")
plt.xlabel("MI Score")
plt.gca().invert_yaxis()
plt.show()

"""---


# **CHURN PREDICTION MODEL**

---


# **1. Chọn các biến đầu vào dựa theo Ma trận tương quan và Mutual Infomation**
"""

selected_features = [
    "ExternalTransfers",
    "TransferLoginRatio",
    "NumOfProducts",
    "Age",
    'Gender',
    "IsActiveMember",
    'LoginFrequency',
    'Balance',
    "BalancePerProduct",
    "SalaryPerAge",
    "ActivityPerTenure"
]

"""




 #  **2. Chia dữ liệu huẩn luyện**





  ### **Tách test set trước – 20%**

    - X_test, y_test sẽ là tập test cuối cùng – chỉ dùng sau cùng để đánh giá mô hình đã huấn luyện.

    - Dùng stratify=y để đảm bảo tỉ lệ churn (Exited = 1) trong tập test giống với toàn bộ tập dữ liệu, tránh bị lệch.

    - random_state=42 để tái lập kết quả.

   ### **Tách Calibration set – 10% của tổng, tương đương 12.5% phần còn lại**

    - X_calib, y_calib: Tập calibration – dùng để tạo ra khoảng tin cậy trong dự đoán (sử dụng thư viện MAPIE).

    - X_train, y_train: Tập huấn luyện chính.

    - Vì tách 12.5% của phần còn lại (80% dữ liệu ban đầu), nên:

      - X_train = 70%

      - X_calib = 10%

      - X_test = 20%

"""

from sklearn.model_selection import train_test_split

# Lấy input đầu vào
X_scaled = df[selected_features]
y = df["Exited"]

# # 1. Tách test trước (20%)
# X_temp, X_test, y_temp, y_test = train_test_split(
#     X_scaled, y, test_size=0.2, stratify=y, random_state=42
# )

# # 2. Tách calib từ phần còn lại (10% → 12.5% của X_temp)
# X_train, X_calib, y_train, y_calib = train_test_split(
#     X_temp, y_temp, test_size=0.125, stratify=y_temp, random_state=42
# )

"""# **3. Machine Learning**

### **Trong dự án này, tôi đã triển khai 3 mô hình classification chính để dự đoán churn:**

- Random Forest (RF)

- XGBoost

- LightGBM

Các mô hình này:

 - Không cần scale dữ liệu

 - Xử lý tốt các mối quan hệ phi tuyến

 - Chịu được noise và feature dư thừa

Ngoài ra:

 - Với dữ liệu mất cân bằng (Exited = 1 chỉ ~20%), đã sử dụng tham số:

 - class_weight='balanced' cho RF và LGBM

 - scale_pos_weight cho XGBoost
"""

!pip install shap -U

# !pip install skorch

"""##MLP"""

# import torch
# from torch import nn
# from skorch import NeuralNetClassifier
# from sklearn.model_selection import GridSearchCV
# from sklearn.metrics import classification_report
# import numpy as np

# # 1. Định nghĩa MLP class
# class OptimalChurnMLP(nn.Module):
#     def __init__(self, input_units=10, hidden_units=128, dropout=0.3):
#         super().__init__()

#         # Architecture: Input -> 128 -> 64 -> 32 -> 1
#         # Giảm dần theo tỷ lệ 2:1, phù hợp với dataset vừa
#         self.model = nn.Sequential(
#             # Layer 1: Input -> Hidden 1
#             nn.Linear(input_units, hidden_units),
#             nn.BatchNorm1d(hidden_units),  # BatchNorm giúp ổn định training
#             nn.ReLU(),
#             nn.Dropout(dropout),

#             # Layer 2: Hidden 1 -> Hidden 2
#             nn.Linear(hidden_units, hidden_units // 2),
#             nn.BatchNorm1d(hidden_units // 2),
#             nn.ReLU(),
#             nn.Dropout(dropout),

#             # Layer 3: Hidden 2 -> Hidden 3
#             nn.Linear(hidden_units // 2, hidden_units // 4),
#             nn.BatchNorm1d(hidden_units // 4),
#             nn.ReLU(),
#             nn.Dropout(dropout * 0.5),  # Giảm dropout ở layer cuối

#             # Output layer
#             nn.Linear(hidden_units // 4, 1),
#             nn.Sigmoid()
#         )

#     def forward(self, X):
#         return self.model(X).squeeze(-1)

# X_train_torch = X_train.values.astype(np.float32)
# y_train_torch = y_train.values.astype(np.float32)  # Chuyển về float32 cho BCELoss
# X_test_torch = X_test.values.astype(np.float32)
# y_test_torch = y_test.values.astype(np.float32)

# net = NeuralNetClassifier(
#     module=OptimalChurnMLP,
#     module__input_units=X_train.shape[1],
#     module__hidden_units=64,
#     module__dropout=0.3,
#     max_epochs=300,
#     lr=0.001,
#     batch_size=32,
#     optimizer=torch.optim.Adam,
#     criterion=nn.BCELoss,
#     iterator_train__shuffle=True,
#     train_split=None,  # Không sử dụng validation split
#     verbose=1,
#     device='cuda' if torch.cuda.is_available() else 'cpu'
# )

# # 4. Huấn luyện mô hình
# print("Đang huấn luyện MLP...")
# net.fit(X_train_torch, y_train_torch)

# y_pred_mlp = net.predict(X_test_torch)
# y_pred_proba_mlp = net.predict_proba(X_test_torch)[:, 1]  # Lấy xác suất class 1

# print("\n=== Đánh giá MLP ===")
# print(classification_report(y_test, y_pred_mlp, digits=4))

"""### **Random Forest**"""

# from sklearn.ensemble import RandomForestClassifier
# from sklearn.metrics import classification_report, confusion_matrix
# import seaborn as sns
# import matplotlib.pyplot as plt

# rf_model = RandomForestClassifier(
#     n_estimators=500,
#     random_state=42,
#     class_weight='balanced'
# )

# rf_model.fit(X_train, y_train)

# y_pred = rf_model.predict(X_test)
# print(" Đánh giá Random Forest:")
# print(classification_report(y_test, y_pred, digits=4))

# import joblib

# # Lưu model
# joblib.dump(rf_model, "rf_model_final.pkl")
# print(" Đã lưu model RF → rf_model_final.pkl")

"""### **XGBoost**"""

# from xgboost import XGBClassifier
# from sklearn.metrics import classification_report, confusion_matrix

# # Tính scale_pos_weight (tỷ lệ class 0 / class 1)
# scale_weight = y_train.value_counts()[0] / y_train.value_counts()[1]

# xgb_model = XGBClassifier(
#     n_estimators=500,
#     scale_pos_weight=scale_weight,
#     random_state=42
# )

# xgb_model.fit(X_train, y_train)

# y_pred_xgb = xgb_model.predict(X_test)

# # Evaluate
# print(" Đánh giá XGBoost:")
# print(classification_report(y_test, y_pred_xgb, digits=4))

# import joblib
# joblib.dump(xgb_model, "xgb_model_final.pkl")
# print("✅ Đã lưu model → xgb_model_final.pkl")

"""### **LightGBM**"""

# from lightgbm import LGBMClassifier
# from sklearn.metrics import classification_report


# # Train LightGBM
# lgb_model = LGBMClassifier(
#     n_estimators=500,
#     class_weight='balanced',
#     random_state=42
# )

# lgb_model.fit(X_train, y_train)

# # Predict trên test
# y_pred_lgb = lgb_model.predict(X_test)

# # Đánh giá
# print(" Đánh giá LightGBM:")
# print(classification_report(y_test, y_pred_lgb, digits=4))

# import joblib
# joblib.dump(lgb_model, "lgb_model_final.pkl")
# print("✅ Đã lưu LightGBM → lgb_model_final.pkl")

"""##CatBoostClassifier"""

!pip install catboost

from catboost import CatBoostClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, accuracy_score

cat_model = CatBoostClassifier(
    depth=4,
    iterations=300,
    learning_rate=0.1,
    verbose=100,
    random_seed=42
)

cat_model.fit(X_scaled, y)

y_pred = cat_model.predict(X_scaled)
y_pred_proba = cat_model.predict_proba(X_scaled)[:, 1]

print("Accuracy:", accuracy_score(y, y_pred))
print(classification_report(y, y_pred))

import joblib
joblib.dump(cat_model, 'catboost_model.pkl')

"""##Stacking"""

# from sklearn.ensemble import StackingClassifier, RandomForestClassifier
# from xgboost import XGBClassifier
# from lightgbm import LGBMClassifier
# from catboost import CatBoostClassifier
# from sklearn.linear_model import LogisticRegression
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import classification_report, accuracy_score

# # Hoặc sử dụng các mô hình cơ bản nếu chưa GridSearch
# rf = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)
# xgb = XGBClassifier(n_estimators=200, max_depth=5, learning_rate=0.1, use_label_encoder=False, eval_metric='logloss')
# lgb = LGBMClassifier(n_estimators=200, max_depth=7, learning_rate=0.1)
# cat = CatBoostClassifier(iterations=300, learning_rate=0.1, depth=4, verbose=0)

# base_learners = [
#     ('rf', rf),
#     ('xgb', xgb),
#     ('lgb', lgb),
#     ('cat', cat)
# ]

# final_estimator = LogisticRegression(max_iter=1000)

# stack_model = StackingClassifier(
#     estimators=base_learners,
#     final_estimator=final_estimator,
#     cv=5,
#     n_jobs=-1,
#     passthrough=False  # nếu bạn muốn thêm X gốc vào tầng 2 thì để True
# )

# stack_model.fit(X_train, y_train)

# # Dự đoán và đánh giá
# y_pred = stack_model.predict(X_test)

# print("Stacking Accuracy:", accuracy_score(y_test, y_pred))
# print("Classification Report:\n", classification_report(y_test, y_pred))

# joblib.dump(stack_model, "stacking_model.pkl")

"""# **4. Thông số đánh giá**
### **Accuracy (Độ chính xác tổng thể)**

$$
\text{Accuracy} = \frac{TP + TN}{TP + TN + FP + FN}
$$

**Ý nghĩa:**  
- Tỷ lệ dự đoán đúng (churn và không churn) trên toàn bộ mẫu.

**Nhược điểm:**  
 - Không đáng tin khi dữ liệu mất cân bằng.  
**VD:** *nếu chỉ 20% khách hàng churn, đoán tất cả đều không churn cũng được 80% accuracy → tưởng tốt nhưng thực ra tệ*.

**Khi nào dùng:**  
 - Chỉ dùng để tham khảo chung. Không nên là chỉ số chính khi tỷ lệ churn < 50%.

<br>

### **Precision (Độ chính xác dương tính)**

$$
\text{Precision} = \frac{TP}{TP + FP}
$$

**Ý nghĩa:**  
- Trong số khách hàng được **dự đoán sẽ rời bỏ**, bao nhiêu người **thực sự sẽ rời**?

**Ví dụ:**  
- Nếu Precision = 0.85 → trong 100 khách bị báo là sẽ churn, có 85 người thật sự sẽ đi.

**Khi nào dùng:**  
- Quan trọng khi chi phí xử lý khách nhầm cao.  
- Nhưng nếu Precision cao mà Recall thấp thì mô hình "chơi an toàn", chỉ báo churn khi rất chắc → bỏ sót nhiều khách thật sự rời đi.

<br>

### **Recall (Độ nhạy)**

$$
\text{Recall} = \frac{TP}{TP + FN}
$$

**Ý nghĩa:**  
- Trong số khách hàng **thực sự rời bỏ**, mô hình **bắt được bao nhiêu**?

**Ví dụ:**  
- Nếu Recall = 0.90 → có 100 người thật sự sẽ rời, mô hình bắt được 90 người.

**Khi nào dùng:**  
 Rất quan trọng trong dự án churn vì:
- Bỏ sót khách sắp rời là **mất tiền thật**.
- Dự đoán sai còn xử lý được (ví dụ gọi điện hỏi thăm), nhưng bỏ qua thì mất luôn.

<br>

### **F1-Score (Chỉ số cân bằng Precision và Recall)**

$$
\text{F1} = 2 \times \frac{\text{Precision} \times \text{Recall}}{\text{Precision} + \text{Recall}}
$$

**Ý nghĩa:**  
F1-score là chỉ số tổng hợp giữa độ chính xác (Precision) và độ nhạy (Recall).  
Nếu một trong hai thấp, F1 sẽ phản ánh điều đó. F1-score là thước đo tốt khi cần cân bằng giữa việc tránh bỏ sót và tránh báo nhầm.

**Khi nào sử dụng:**  
- Khi dự án yêu cầu mô hình phải bắt được đúng khách hàng rời bỏ nhưng cũng hạn chế báo nhầm.  
- Thích hợp với các bài toán như churn prediction, fraud detection, medical diagnosis.

**Sau khi tính Precision, Recall, F1-score cho từng lớp (class 0: không rời, class 1: rời), ta cần tổng hợp kết quả chung. sklearn cung cấp hai dạng trung bình:**

<br>

### **Macro Average**

**Cách tính:**  
Tính trung bình cộng của chỉ số trên tất cả các lớp mà **không xét đến tỉ lệ số lượng** giữa các lớp.

Ví dụ cho F1-score:

$$
\text{F1}_{macro} = \frac{\text{F1}_{class\ 0} + \text{F1}_{class\ 1}}{2}
$$

**Ý nghĩa:**  
- Đánh giá mô hình công bằng giữa các lớp.
- Phù hợp khi cần mô hình thể hiện tốt cho **cả hai lớp**, dù dữ liệu mất cân bằng.

<br>

### **Weighted Average**

**Cách tính:**  
Tính trung bình cộng có trọng số, trọng số là số lượng mẫu tương ứng ở mỗi lớp.

Ví dụ cho F1-score:

$$
\text{F1}_{weighted} = \frac{\text{F1}_0 \cdot N_0 + \text{F1}_1 \cdot N_1}{N_0 + N_1}
$$

**Ý nghĩa:**  
- Phản ánh đúng hiệu suất tổng thể của mô hình trên toàn bộ dữ liệu.
- Tuy nhiên có thể **che khuất điểm yếu của mô hình ở lớp thiểu số**, do lớp đông hơn chiếm nhiều trọng số.

<br>

### **Lưu ý khi áp dụng cho bài toán churn prediction:**

- `Recall` và `F1-score` của lớp **Exited = 1** (khách hàng rời) là chỉ số quan trọng nhất.
- `Macro average` giúp đánh giá xem mô hình có đang thiên lệch không.
- `Weighted average` chỉ nên dùng để đánh giá tổng thể, không phản ánh chính xác hiệu quả của mô hình trên lớp churn (nếu mất cân bằng).

# **5. So sánh mô hình**

- Dựa vào bộ chỉ số đầu ra và ma trận nhầm lẫn của các mô hình ta có thể so sánh và chọn ra mô hình sẽ tích hợp SHAP và MAPIE để đưa vào hệ thống sau cùng.
"""

# # Load tất cả các mô hình đã huấn luyện
# rf_model = joblib.load('rf_model_final.pkl')
# xgb_model = joblib.load('xgb_model_final.pkl')
# lgb_model = joblib.load('lgb_model_final.pkl')

# import matplotlib.pyplot as plt
# import seaborn as sns
# from sklearn.metrics import confusion_matrix

# # Dự đoán từ các mô hình
# y_pred_rf = rf_model.predict(X_test)
# y_pred_xgb = xgb_model.predict(X_test)
# y_pred_lgb = lgb_model.predict(X_test)

# # Vẽ Confusion Matrix cho mỗi mô hình
# fig, axs = plt.subplots(2, 2, figsize=(14, 12))

# # Random Forest
# cm_rf = confusion_matrix(y_test, y_pred_rf)
# sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Blues', ax=axs[0, 0])
# axs[0, 0].set_title("Confusion Matrix - RF")
# axs[0, 0].set_xlabel("Predicted")
# axs[0, 0].set_ylabel("Actual")

# # XGBoost
# cm_xgb = confusion_matrix(y_test, y_pred_xgb)
# sns.heatmap(cm_xgb, annot=True, fmt='d', cmap='Greens', ax=axs[0, 1])
# axs[0, 1].set_title("Confusion Matrix - XGBoost")
# axs[0, 1].set_xlabel("Predicted")
# axs[0, 1].set_ylabel("Actual")

# # LightGBM
# cm_lgb = confusion_matrix(y_test, y_pred_lgb)
# sns.heatmap(cm_lgb, annot=True, fmt='d', cmap='Oranges', ax=axs[1, 0])
# axs[1, 0].set_title("Confusion Matrix - LightGBM")
# axs[1, 0].set_xlabel("Predicted")
# axs[1, 0].set_ylabel("Actual")

# plt.tight_layout()
# plt.show()

# # Create classification report for each model
# report_rf = classification_report(y_test, y_pred_rf, output_dict=True)
# report_xgb = classification_report(y_test, y_pred_xgb, output_dict=True)
# report_lgb = classification_report(y_test, y_pred_lgb, output_dict=True)

# # Convert each classification report into a DataFrame
# df_rf = pd.DataFrame(report_rf).T
# df_xgb = pd.DataFrame(report_xgb).T
# df_lgb = pd.DataFrame(report_lgb).T

# # Combine the DataFrames for comparison
# df_comparison = pd.concat([df_rf[['precision', 'recall', 'f1-score']],
#                            df_xgb[['precision', 'recall', 'f1-score']],
#                            df_lgb[['precision', 'recall', 'f1-score']]],
#                           axis=1)

# # Rename the columns for clarity
# df_comparison.columns = ['RF - Precision', 'RF - Recall', 'RF - F1-Score',
#                          'XGBoost - Precision', 'XGBoost - Recall', 'XGBoost - F1-Score',
#                          'LightGBM - Precision', 'LightGBM - Recall', 'LightGBM - F1-Score']

# # Display the comparison table directly in Colab
# df_comparison

"""---
# **GIẢI THÍCH MÔ HÌNH VỚI SHAP**
---

# **SHAP là gì và tại sao cần dùng?**
### **SHAP (SHapley Additive exPlanations) là một phương pháp giúp giải thích đầu ra của mô hình Machine Learning**
 - Nó trả lời câu hỏi: “Tại sao mô hình dự đoán khách hàng này sẽ rời bỏ?”

 - Thay vì chỉ biết một con số xác suất churn, SHAP giúp chúng ta thấy được các yếu tố nào đang kéo xác suất đó lên hoặc xuống, giúp mô hình trở nên minh bạch và dễ tin hơn với người dùng kinh doanh.

### **Ứng dụng trong dự án Churn Prediction**
Trong dự án này, chúng tôi áp dụng SHAP để:

 - Giải thích các yếu tố ảnh hưởng đến từng quyết định dự đoán churn.

 - Trực quan hóa vai trò của từng biến đầu vào.

 - Tạo sự minh bạch, tăng độ tin tưởng từ phía khách hàng và phòng kinh doanh.
"""

# !pip install --upgrade shap

# import joblib
# import json
# import os

# # Tạo thư mục nếu chưa có
# os.makedirs("models", exist_ok=True)

# # SAVE feature list đúng thứ tự cột lúc train
# with open("models/feature_list.json", "w") as f:
#     json.dump(list(X_train.columns), f)

# import shap
# import joblib
# import json

# # Load model
# model = joblib.load("/content/stacking_model.pkl")

# # Load đúng thứ tự feature
# with open("/content/models/feature_list.json") as f:
#     feature_list = json.load(f)

# X_test = X_test[feature_list]

# # Lấy model CatBoost từ Stacking
# cat_model = dict(model.named_estimators_)['cat']

# # Dùng SHAP với CatBoost
# explainer = shap.TreeExplainer(cat_model)
# shap_values = explainer.shap_values(X_test)

"""


# **SHAP Bar Plot (Feature Importance tổng thể)**


- Trung bình độ ảnh hưởng của mỗi biến đến dự đoán trên toàn bộ khách hàng.

  - Từ biểu đồ ta thấy ExternalTransfers có tác động lớn nhất đến mô hình.

  - Tiếp theo là BalancePerProduct, SalaryPerAge, Age, v.v.

- Ý nghĩa:
  - Giúp team kinh doanh hiểu biến nào đang thực sự quan trọng với mô hình – từ đó tập trung cải thiện/thu thập thêm thông tin cho các biến này.


<br>


# **SHAP Summary Plot (Violin plot)**



- Kết hợp giữa giá trị biến và mức độ ảnh hưởng để thấy xu hướng hành vi toàn bộ hệ thống.


- Trục ngang: SHAP value (mức độ ảnh hưởng).

- Màu sắc: Giá trị của feature (Xanh: thấp, Hồng: cao).

- Ví dụ phân tích:

  - Với ExternalTransfers: giá trị thấp (xanh) thường kéo SHAP về âm → khả năng rời đi tăng cao khi ít giao dịch ra ngoài.

  - Với BalancePerProduct: giá trị thấp cũng thường đẩy dự đoán lên → tức là khách có tài khoản nhưng không dùng sản phẩm có khả năng rời cao.

- Ý nghĩa:
  - Cho thấy mối quan hệ logic giữa hành vi và churn trên toàn hệ thống. Điều này giúp validate mô hình, đảm bảo mô hình "nghĩ đúng".
"""

# shap.summary_plot(shap_values, X_test, plot_type="bar")
# shap.summary_plot(shap_values, X_test)

"""

# **SHAP Force Barplot**

 Force plot (SHAP Decision Explanation)
 - Mỗi biểu đồ là một cá nhân – mô hình đã quyết định họ rời hay không, và SHAP cho thấy lý do.

  - Màu đỏ: Các biến làm tăng khả năng rời bỏ.

  - Màu xanh: Các biến làm giảm khả năng rời bỏ.

Trục ngang thể hiện mức độ ảnh hưởng (âm hay dương) tới đầu ra mô hình.

- Ví dụ giải thích:

  - ExternalTransfers = 13 làm giảm mạnh khả năng rời bỏ → khách này giao dịch ra ngoài nhiều, có thể vẫn đang tương tác tích cực.

  - BalancePerProduct = 0 làm tăng khả năng rời bỏ → khách có tài khoản nhưng không sử dụng sản phẩm → tiềm năng rời đi cao.

 ⟶ Giúp nhân viên CSKH hiểu lý do tại sao hệ thống đánh giá như vậy, từ đó hành động đúng hướng.



"""

# shap.plots.waterfall(shap.Explanation(
#     values=shap_values[0],
#     base_values=explainer.expected_value,
#     data=X_test.iloc[0]
# ))

# shap.plots.waterfall(shap.Explanation(
#     values=shap_values[1],
#     base_values=explainer.expected_value,
#     data=X_test.iloc[1]
# ))

"""# **Giải thích các chỉ số trong SHAP Force Plot**




SHAP force plot là biểu đồ trực quan mô tả lý do tại sao mô hình đưa ra một dự đoán cụ thể cho từng khách hàng. Dưới đây là các thành phần chính trong biểu đồ:


### **1. `f(x)` – Giá trị đầu ra của mô hình**

$$
f(x) = \text{logit score}
$$

- Là giá trị đầu ra (log-odds) của mô hình cho một cá nhân cụ thể.
- Được dùng để tính xác suất bằng hàm sigmoid:

$$
\text{Probability} = \frac{1}{1 + e^{-f(x)}}
$$

- Nếu `f(x)` âm → xác suất churn thấp. Nếu `f(x)` dương → xác suất churn cao.

**Ví dụ:**  
`f(x) = -13.45` → xác suất churn gần bằng 0%.

<br>


### **2. `E[f(X)]` – Giá trị trung bình mô hình**

- Là giá trị đầu ra trung bình của mô hình trên toàn bộ tập dữ liệu huấn luyện.
- Là điểm khởi đầu cho mọi dự đoán trước khi thêm ảnh hưởng của từng biến.

**Ý nghĩa:**  
Nếu không có thông tin gì về khách hàng, mô hình mặc định dự đoán bằng `E[f(X)]`.

**Ví dụ:**  
`E[f(X)] = -5.625` → baseline của toàn bộ hệ thống.

<br>

### **3. Các mũi tên (các biến đầu vào)**

- **Màu đỏ:** Biến này đang **làm tăng xác suất churn**.
- **Màu xanh:** Biến này đang **giảm xác suất churn**.
- **Chiều dài mũi tên:** Mức độ ảnh hưởng của biến đó.

**Ví dụ:**  
- `ExternalTransfers = 13 → -8.9`  
Khách chuyển tiền ra ngoài nhiều → được coi là đang hoạt động tích cực → giảm mạnh khả năng churn.

- `BalancePerProduct = 0 → +1.86`  
Khách có tài khoản nhưng không dùng sản phẩm → khả năng churn tăng.

<br>

### **4. Tổng hợp: Công thức SHAP**

Biểu đồ force plot hoạt động theo công thức:

$$
f(x) = E[f(X)] + \sum_{i=1}^{n} \text{SHAP}_i
$$

Tức là: mô hình bắt đầu từ điểm trung bình và cộng/trừ ảnh hưởng của từng biến để đi đến quyết định cuối cùng.

---


# **TẠO KHOẢNG TIN CẬY VỚI MAPIE**

---

# **Giới thiệu về MAPIE**




**MAPIE** (Model Agnostic Prediction Interval Estimator) là một thư viện Python hỗ trợ tạo **khoảng dự đoán (prediction intervals)** hoặc **tập dự đoán (prediction sets)** cho các mô hình học máy, dựa trên phương pháp conformal prediction.

Khác với mô hình truyền thống chỉ đưa ra một kết quả duy nhất, MAPIE cho phép dự đoán **nhiều khả năng xảy ra**, cùng với **mức độ tin cậy xác định trước** (ví dụ: 90%, 95%).

MAPIE hỗ trợ cả:
- Phân loại (Classification)
- Hồi quy (Regression)



# **Cách hoạt động của MAPIE**

MAPIE hoạt động theo các bước sau:

1. **Tách một phần dữ liệu làm calibration set (tập hiệu chỉnh)**.
2. **Huấn luyện mô hình như bình thường trên phần còn lại**.
3. **Tính toán sai số dự đoán hoặc xác suất trên tập calibration**.
4. **Sinh ra khoảng/tập dự đoán dựa trên phân bố sai số và tham số `alpha` do người dùng cung cấp**.


# **Các tham số quan trọng trong MAPIE**

### **Alpha**

- Đại diện cho mức độ sai số cho phép.
- Công thức:

  ```
  alpha = 1 - độ tin cậy mong muốn
  ```

- Ví dụ: Nếu yêu cầu độ tin cậy 95%, thì:

  ```
  alpha = 1 - 0.95 = 0.05
  ```


### **Coverage**

- Là tỷ lệ các điểm test mà prediction interval (hoặc prediction set) **bao phủ đúng giá trị thực tế**.
- Dùng để đánh giá chất lượng dự đoán của mô hình sau khi áp dụng MAPIE.


# **Vai trò trong dự án**

MAPIE không thay thế mô hình gốc.  
Thay vào đó, nó hoạt động như một **lớp bổ sung** giúp:

- Tăng độ tin cậy cho mô hình dự đoán.
- Cung cấp thông tin xác suất và mức độ chắc chắn.
- Hỗ trợ người dùng ra quyết định tốt hơn.

Ví dụ: hệ thống không chỉ dự đoán "khách hàng này sẽ churn", mà còn đưa ra khoảng tin cậy: "Dự đoán này đúng với xác suất 90%".

# **Các bước triển khai:**

1. **Chia dữ liệu thành 3 phần:**  
   - Train (70%)  
   - Calibration (10%)  
   - Test (20%)

   Khác với thông thường chỉ chia Train/Test.

2. **Huấn luyện mô hình trên tập Train.**

3. **Áp dụng MAPIE trên tập Calibration:**
   - Tính toán xác suất phân loại cho từng mẫu.
   - Ước lượng ngưỡng để prediction set đạt coverage thực tế ≥ (1 - alpha).

4. **Dự đoán trên tập Test:**
   - Trả về prediction set với độ tin cậy cụ thể (ví dụ: 95%).
"""

# !pip install -U mapie

# import mapie.classification
# dir(mapie.classification)

# !pip install git+https://github.com/scikit-learn-contrib/MAPIE

# from mapie.utils import train_conformalize_test_split
# from mapie.classification import SplitConformalClassifier
# from mapie.metrics.classification import classification_coverage_score


# catboost_model = joblib.load('lgb_model_final.pkl')

# confidence_level = 0.95
# mapie_classifier = SplitConformalClassifier(
#     estimator=catboost_model, confidence_level=confidence_level, prefit=True
# )
# mapie_classifier.conformalize(X_calib, y_calib)
# y_pred, y_pred_set = mapie_classifier.predict_set(X_test)

# coverage_score = classification_coverage_score(y_test, y_pred_set)
# print(f"For a confidence level of {confidence_level:.2f}, "
#       f"the target coverage is {confidence_level:.3f}, "
#       f"and the effective coverage is {coverage_score[0]:.3f}.")

# from matplotlib.colors import ListedColormap

# x_min, x_max = np.min(X[:, 0]), np.max(X[:, 0])
# y_min, y_max = np.min(X[:, 1]), np.max(X[:, 1])
# step = 0.1

# xx, yy = np.meshgrid(np.arange(x_min, x_max, step), np.arange(y_min, y_max, step))
# X_test_mesh = np.stack([xx.ravel(), yy.ravel()], axis=1)

# # Lấy kết quả dự đoán tập hợp
# _, y_pred_set_df = mapie_classifier.predict_set(X_test_mesh)

# # Ép hoàn toàn sang NumPy
# y_pred_set_np = y_pred_set_df.to_numpy()

# # Bây giờ mới slice
# y_pred_set = y_pred_set_np[:, :, 0]


# cmap_back = ListedColormap(
#     [(0.7803921568627451, 0.9137254901960784, 0.7529411764705882),
#      (0.9921568627450981, 0.8156862745098039, 0.6352941176470588),
#      (0.6196078431372549, 0.6039215686274509, 0.7843137254901961),
#      (0.7764705882352941, 0.8588235294117647, 0.9372549019607843),
#      (0.6196078431372549, 0.6039215686274509, 0.7843137254901961),
#      (0.6196078431372549, 0.6039215686274509, 0.7843137254901961)]
# )
# cmap_dots = ListedColormap(
#     [(0.19215686274509805, 0.5098039215686274, 0.7411764705882353),
#      (0.9019607843137255, 0.3333333333333333, 0.050980392156862744),
#      (0.19215686274509805, 0.6392156862745098, 0.32941176470588235)]
# )

# plt.scatter(
#    X_test_mesh[:, 0], X_test_mesh[:, 1],
#    c=np.ravel_multi_index(y_pred_set.T, (2, 2, 2)),
#    cmap=cmap_back, marker='.', s=10
# )
# plt.scatter(X[:, 0], X[:, 1], c=y, cmap=cmap_dots)
# plt.xlabel("x1")
# plt.ylabel("x2")
# plt.title("Confidence regions with KNN")
# plt.show()

# from mapie.metrics.classification import classification_coverage_score, classification_mean_width_score

# alpha_values = np.arange(0.01, 0.98, 0.01)

# coverages_score = []
# widths_score = []

# # Loop qua từng alpha value
# for alpha in alpha_values:
#     # Tạo classifier mới cho mỗi alpha (confidence_level = 1 - alpha)
#     confidence_level = 1 - alpha

#     mapie_temp = SplitConformalClassifier(
#         estimator=catboost_model,
#         prefit=True
#     )
#     mapie_temp.conformalize(X_calib, y_calib)

#     # Predict với confidence level này
#     _, y_pred_set_temp = mapie_temp.predict_set(X_test)

#     # Tính coverage và width
#     cov = classification_coverage_score(y_test, y_pred_set_temp)
#     wid = classification_mean_width_score(y_pred_set_temp)

#     coverages_score.append(cov)
#     widths_score.append(wid)

# # Hàm vẽ
# def plot_coverages_widths(alpha, coverage, width, method):
#     fig, axs = plt.subplots(1, 2, figsize=(12, 5))

#     # Coverage
#     axs[0].scatter(1 - alpha, coverage, label=method, alpha=0.7)
#     axs[0].set_xlabel("1 - alpha (Confidence Level)")
#     axs[0].set_ylabel("Coverage Score")
#     axs[0].plot([0, 1], [0, 1], label="Ideal (x=y)", color="red", linestyle="--")
#     axs[0].legend()
#     axs[0].grid(True, alpha=0.3)
#     axs[0].set_title("Coverage vs Confidence Level")

#     # Width
#     axs[1].scatter(1 - alpha, width, label=method, alpha=0.7, color='orange')
#     axs[1].set_xlabel("1 - alpha (Confidence Level)")
#     axs[1].set_ylabel("Average Size of Prediction Sets")
#     axs[1].legend()
#     axs[1].grid(True, alpha=0.3)
#     axs[1].set_title("Prediction Set Width vs Confidence Level")

#     plt.tight_layout()
#     plt.show()

# # Vẽ đồ thị
# plot_coverages_widths(alpha_values, coverages_score, widths_score, "SplitConformalClassifier")

# # Lưu ra dataframe
# results = pd.DataFrame({
#     'alpha': alpha_values,
#     'confidence_level': 1 - alpha_values,
#     'coverage': coverages_score,
#     'width': widths_score
# })

# # Xem kết quả
# print("Results (first 20 rows):")
# print(results.head(20))

# print(f"\nSummary statistics:")
# print(f"Alpha range: {alpha_values.min():.3f} - {alpha_values.max():.3f}")
# # print(f"Coverage range: {min(coverages_score):.3f} - {max(coverages_score):.3f}")
# # print(f"Width range: {min(widths_score):.3f} - {max(widths_score):.3f}")

# # Tìm alpha tối ưu (coverage gần nhất với confidence level)
# results['coverage_diff'] = abs(results['coverage'] - results['confidence_level'])
# optimal_idx = results['coverage_diff'].idxmin()
# optimal_result = results.loc[optimal_idx]

# print(f"\nOptimal configuration:")
# print(f"Alpha: {optimal_result['alpha']:.3f}")
# print(f"Confidence Level: {optimal_result['confidence_level']:.3f}")
# print(f"Actual Coverage: {optimal_result['coverage']:.3f}")
# print(f"Average Width: {optimal_result['width']:.3f}")

"""- **Mục đích của biểu 1 trên là để** : Đo mức độ mà prediction set thực tế bao phủ đúng nhãn thật so với độ tin cậy kỳ vọng của người dùng.

  - Mô hình được calibrate rất tốt: coverage thực tế ≈ độ tin cậy đặt ra.
  - Không bị quá tự tin (coverage < kỳ vọng) hay quá dè chừng (coverage >> kỳ vọng).
  - Đây là dấu hiệu mô hình có thể được dùng an toàn trong hệ thống thực tế mà không cần tuning thêm.



- **Mục đích của biểu đồ 2** này giup ta đo mức độ “rộng” của tập dự đoán khi ta yêu cầu mô hình có độ tin cậy cao hơn.
  -	Prediction set có kích thước trung bình tăng tuyến tính và hợp lý theo yêu cầu độ tin cậy.
  -	Ở độ tin cậy thấp khiến prediction set nhỏ (≈ 1 nhãn), phù hợp để tự động hóa
  -	Ở độ tin cậy cao dẫn đến prediction set mở rộng từ từ và đảm bảo không bỏ sót nhưng vẫn giữ tính cụ thể cao

  - Cho thấy mô hình rất “tự tin khi nên” và “cẩn thận khi cần” → cực kỳ thích hợp để đưa vào các pipeline có yếu tố quyết định tự động + kiểm soát rủi ro.

- Tiếp đến chúng tôi quan sát bảng thống kê thông số của alpha, coverage, width để chọn ra alpha phù hợp nhất. Mục tiêu là cân bằng giữa coverage với width theo alpha

  - Tức là coverages sẽ sát với 1-alpha (độ tin cậy). Lúc này mô hình đạt đúng mức độ tin cậy kỳ vọng. Không overconfident (nguy hiểm), cũng không quá dè chừng (thiếu hiệu quả).
Width càng gần 1 càng tốt. Vì trong trường hợp Width = 1 thì Prediction set chỉ chứa đúng 1 nhãn duy nhất, và nhãn đó chính là nhãn đúng.

  - Để tìm ra điểm trade-off hợp lí. Tức là điểm mà mô hình dự đoán đúng nhiều nhất và trả lại ít hồ sơ cần người dung phải tự xem xét nhất có thể tức là nó trả về nhiều set có nhiều giá trị.

# **MAPIE tính cận trên và dưới như thế nào?**

### **Bước 1: Tính xác suất trên tập calibration (`X_cal`)**

Gọi:
- ^Pi: xác suất dự đoán class 1 của mẫu \( i \)  
- \( y_i \): nhãn thật của mẫu \( i \)

<br>

### **Bước 2: Tính conformity score**

$$
s_i =
\begin{cases}
1 - \hat{p}_i, & \text{nếu } y_i = 1 \\
\hat{p}_i, & \text{nếu } y_i = 0
\end{cases}
$$

Score này cho biết mô hình đã sai lệch bao nhiêu so với thực tế.

<br>

### **Bước 3: Tính quantile tương ứng với alpha**

Với alpha = 0.05, ta tính:

$$
q_\alpha = \text{Quantile}_{1 - \alpha}(s_i)
$$

<br>

### **Bước 4: Tính cận dưới và cận trên cho điểm test**

Với xác suất dự đoán :

$$
\text{Lower} = \max(0, \hat{p}_{\text{test}} - q_\alpha)
$$

$$
\text{Upper} = \min(1, \hat{p}_{\text{test}} + q_\alpha)
$$

Điều này đảm bảo rằng, với xác suất ít nhất là \( 1 - \alpha \), giá trị thực của xác suất sẽ nằm trong khoảng trên.

<br>

### **Ví dụ minh họa**

Giả sử:
- \( alpha = 0.05 \)
- \( q_{0.05} = 0.15 \)
- \( q_test = 0.88 \)

Tính:

$$
\text{Lower} = 0.88 - 0.15 = 0.73
$$

$$
\text{Upper} = clip(1.00, 0.88 + 0.15) = 1.00
$$

→ Prediction interval: [0.73, 1.00]

<br>

### **Kết luận**

$$
\boxed{
\begin{aligned}
\text{Lower} &= \max(0, \hat{p}_{\text{test}} - q_\alpha) \\
\text{Upper} &= \min(1, \hat{p}_{\text{test}} + q_\alpha)
\end{aligned}
}
$$
"""

# interval_df = pd.DataFrame({
#     'y_test': y_test.values,
#     'Prob Lower': np.round(prob_lower, 2),
#     'Prob Class 1': np.round(prob_test, 2),
#     'Prob Upper': np.round(prob_upper, 2),

# })
# display(interval_df.head(10))

# from mapie.classification import MapieClassifier
# from mapie.metrics import (classification_coverage_score,
#                            classification_mean_width_score)

# # Mapie Classfier để train mô hình gốc trên tập cal để dự báo Prediction Set cho tập test
# mapie_score = MapieClassifier(estimator=lgb_model, cv="prefit", method="lac")
# mapie_score.fit(X_calib, y_calib)
# _, y_pred_set = mapie_score.predict(X_test, alpha = alpha)

# # Thêm kết quả pred set vào df ở trên
# interval_df['Set'] = [set(np.where(row)[0]) for row in y_pred_set[:, :, 0]]
# interval_df.head(20)